version: 0.0
os: linux
files:
  - source: myapp.zip
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
