version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Build step complete"

artifacts:
  files:
    - appspec.yml
    - app.py
    - scripts/**/*
