version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Zipping application and deployment files"
      - zip -r myapp.zip app.py scripts/ appspec.yml
artifacts:
  files:
    - myapp.zip
